import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Albert Yan</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Personal site updated soon</h1>
      </main>

      <footer className={styles.footer}>
        <p>Last Updated March 26, 2022</p>
      </footer>
    </div>
  );
};

export default Home;
